name: VAETO_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nvidia::cudatoolkit=11.1
  - numpy
  - python=3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - wandb
  - pandas
  - scikit-learn
