name: VAETO_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nvidia::cudatoolkit=12.1
  - numpy
  - python=3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::wandb
  - pandas
  - conda-forge::scikit-learn
  - conda-forge::anndata
