name: VAETO_env
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - python=3.8
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::wandb
  - pandas
  - conda-forge::scikit-learn
  - conda-forge::cellrank
  - matplotlib 
