name: VAETO_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nvidia::cudatoolkit=11.1
  - numpy
  - python=3.9
  - pytorch::pytorch=1.9
  - pytorch::torchvision=0.10
  - conda-forge::wandb
  - pandas
  - conda-forge::scikit-learn
